site_name: pytest-deadfixtures
site_description: A simple plugin to use with Pytest
site_author: João Luiz Lorencetti

theme: readthedocs

repo_url: https://github.com/jllorencetti/pytest-deadfixtures

pages:
- Home: index.rst
